{% set name = "spyder-modelx" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyder-modelx-{{ version }}.tar.gz
  sha256: c3086ceac43709be02db0f5b4e23ce310552daedd364824ad52ba943ef4c4b8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - modelx >=0.18.0
    - python >=3.6
    - spyder >=4.0.0
    - spymx-kernels >=0.1.1

test:
  imports:
    - spyder_modelx
  commands:
    - pip check  # [linux or win]
  requires:
    - pip

about:
  home: https://github.com/fumitoh/spyder-modelx
  summary: Spyder plugin for modelx
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
