{% set name = "spyder-modelx" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyder-modelx-{{ version }}.tar.gz
  sha256: e4c2274dda3a39902facd267ed225fe2faed81ce0ba1713fd38b9783c7796368

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - modelx >=0.18.0
    - python >=3.6
    - spyder >=4.0.0
    - spymx-kernels >=0.1.1
    - pyqt ==5.9.2

test:
  imports:
    - spyder_modelx
  commands:
    - pip check  # [linux or win]
  requires:
    - pip

about:
  home: https://github.com/fumitoh/spyder-modelx
  summary: Spyder plugin for modelx
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
