{% set name = "spyder-modelx" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7e3dc57a76aed44da272274494e033704fab164cc04b73125359b4747b8231bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - asttokens
    - modelx >=0.18.0
    - python >={{ python_min }}
    - spyder <6.0.0
    - spymx-kernels >=0.1.1

test:
  imports:
    - spyder_modelx
  commands:
    - pip check  # [linux or win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fumitoh/spyder-modelx
  summary: Spyder plugin for modelx
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
